pre_seq_length: 11
aft_seq_length: 11
total_length: 22
batch_size: 4
val_batch_size: 4
epoch: 50
lr: 0.001
metrics: 
  - 'iou'
dataname: 'custom'
res_dir: 'weights_hub'
data_root: './dataset'
pretrain: 'pretrain_e3lr3oc_eps05'
load_vp: True
fix_vp: True
load_unet: False
fix_unet: False
gpus:
  - 0
num_workers: 2

