pre_seq_length: 11
aft_seq_length: 11
total_length: 22
batch_size: 8
val_batch_size: 8
epoch: 50
lr: 0.001
metrics: 
  - 'iou'
dataname: 'custom'
in_shape: [11, 3, 160, 240]
res_dir: 'weights_hub'
pretrain: 'pretrain_e3lr3_eps05'
load_vp: True
fix_vp: True
load_unet: False
fix_unet: False
gpus:
  - 0
  - 1


