pre_seq_length: 11
aft_seq_length: 11
total_length: 22
batch_size: 6
val_batch_size: 6
epoch: 20
lr: 0.001
min_lr: 0.00001
metrics: 
  - 'iou'
dataname: 'custom'
in_shape: [11, 1, 160, 240]
eps: 1
res_dir: 'weights_hub'
data_root: '../dataset'
vis_val: True
gpus:
  - 0
  - 1
  - 2
  - 3
num_workers: 11
test: False