pre_seq_length: 11
aft_seq_length: 11
total_length: 22
batch_size: 8
val_batch_size: 8
epoch: 10
lr: 0.001
metrics: 
  - 'iou'
dataname: 'custom'
res_dir: 'weights_hub'
data_root: './dataset'
vis_val: True
gpus:
  - 0
num_workers: 2
test: False
