pre_seq_length: 11
aft_seq_length: 11
total_length: 22
batch_size: 8
val_batch_size: 8
epoch: 20
lr: 0.001
metrics: 
  - 'mse'
  - 'mae'
  - 'ssim'
dataname: 'custom'
eps: 0.5
res_dir: 'weights_hub'
data_root: ./dataset'
gpus:
  - 0
  - 1
  - 2
  - 3
num_workers: 11

