pre_seq_length: 11
aft_seq_length: 11
total_length: 22
batch_size: 4
val_batch_size: 4
epoch: 20
lr: 0.001
metrics: 
  - 'mse'
  - 'mae'
  - 'ssim'
dataname: 'custom'
eps: 1
data_root: './dataset'
res_dir: 'weights_hub'
gpus:
  - 0
  - 1
  - 2
  - 3
num_workers: 11

